import { StyleSheet } from "react-native";


const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
  },
  iwmage: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    borderRadius: 12,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    backgroundColor: 'white',
    height: 220,
  },
  metaBalance: {
    resizeMode: 'cover',
    padding: 18,
    borderRadius: 12,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    backgroundColor: 'white',
    marginRight: 15,
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  metaBalance2: {
    resizeMode: 'cover',
    padding: 18,
    borderRadius: 12,
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    backgroundColor: 'white',
    marginLeft: 15,
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',

    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  metaBalanceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  balanceContainer: {
    alignContent: 'flex-start',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexDirection: 'row',
    // backgroundColor: '#359ce6',
    borderRadius: 12,
    height: 220,
    marginTop: 25,
    width: 375,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  balance: {
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'center',
    width: 375,
  },
  rightBalanceText: {
    fontWeight: '500',
    // // alignSelf: 'flex-start',
    fontSize: 15,
    marginBottom: 5,
    // // justifyContent: 'flex-start',
    // position: 'relative',
    // top: 26,
    // color: 'black',
  },
  leftBalanceText: {
    fontWeight: '400',
    marginLeft: 159,
    fontSize: 12,
  },
  balanceText: {
    fontWeight: '300',
    fontSize: 20,
    marginBottom: 8,
    // marginLeft: 75,
    padding: 1,
    color: 'black',
    fontWeight: '500',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bankImage: {
    width: 170,
    height: 150,
    alignSelf: 'center',
    marginTop: 20,
  },
  money: {
    fontSize: 50,
    paddingRight: 3,
    color: '#007AFF',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  money2: {
    // alignSelf: 'flex-start',
    fontSize: 22,
    // paddingLeft: 10,
    // position: 'relative',
    // top: 47,
    color: '#007AFF',
  },
  money3: {
    alignSelf: 'flex-end',
    fontSize: 30,
    paddingRight: 10,
    color: '#007AFF',
  },
  accountType: {
    fontWeight: '300',
    fontSize: 10,
    fontStyle: 'italic',
  },
  logoImage: {
    // height: 20,
    // resizeMode: "contain",
    width: 60,
    height: 60,
    position: 'absolute',
    alignSelf: 'flex-start',
    top: -28,
    zIndex: 2,
  },
  routingNumber: {
    alignSelf: 'center',
    padding: 20,
    marginTop: 0,
    marginBottom: 0,
    borderRadius: 8,
    width: 300,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  routingNumber2: {
    alignSelf: 'center',
    padding: 20,
    marginTop: 23,
    marginBottom: 0,
    borderRadius: 8,
    width: 300,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  routingTitle: {
    fontSize: 20,
    alignSelf: 'flex-start',
    marginBottom: 3,
  },
  routingDigits: {
    fontSize: 14,
    alignSelf: 'flex-start',
  },
  accountNumber: {
    alignSelf: 'center',
  },
  accountTitle: {
    fontSize: 20,
    alignSelf: 'center',
    marginBottom: 3,
  },
  accountDigits: {
    fontSize: 20,
  },
  phoneNumber: {
    alignSelf: 'center',
    marginTop: 25,
  },
  phoneNumberText: {
    fontSize: 20,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#DCDCDC',
    backgroundColor: 'white',
    paddingLeft: 20,
    paddingRight: 30,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: 4,
  },
  pic: {
    borderRadius: 30,
    width: 63,
    height: 63,
    shadowColor: 'black',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  nameContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 280,
  },
  nameTxt: {
    marginLeft: 10,
    fontWeight: '600',
    color: '#222',
    fontSize: 16,
    width: 160,
  },
  mblTxt: {
    fontWeight: '500',
    color: '#007AFF',
    fontSize: 20,
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  msgContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  msgTxt: {
    fontWeight: '400',
    color: '#008B8B',
    fontSize: 12,
    marginLeft: 15,
  },
  depositTitle: {
    fontSize: 30,
    color: 'black',
    fontWeight: '500',
    marginRight: 45,
    marginLeft: 2,
    padding: 8,
    marginTop: 18,
  },
});

export default styles