import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  graphChartView: {
    width: 350,
    paddingHorizontal: 5,
    paddingVertical: 10,
    backgroundColor: 'white',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderRadius: 16,
  },
  chartView: {
    padding: 5,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderRadius: 16,
  },
  barChartView: {
    padding: 5,
    // justifyContent: 'center',
    // alignContent: 'center',
    // alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderRadius: 18,
  },
  factsView: {
    margin: 5,
    paddingVertical: 25,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'white',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderRadius: 16,
    width: 350,
  },
  graphChartContainer: {
    marginHorizontal: 2,
    marginVertical: 10,
  },
  chartContainer: {
    margin: 10,
  },
  title: {
    justifyContent: 'flex-end',
    alignContent: 'flex-end',
    paddingTop: 20,
    fontWeight: '500',
    fontSize: 17,
  },
  balanceText: {
    fontWeight: '300',
    fontSize: 15,
    marginBottom: 8,
    // marginLeft: 75,
    padding: 1,
    color: 'black',
    fontWeight: '500',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  money: {
    fontSize: 40,
    paddingRight: 3,
    color: '#007AFF',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  money2: {
    fontSize: 40,
    paddingRight: 3,
    color: 'red',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pic: {
    borderRadius: 30,
    width: 30,
    height: 30,
  },
  bankImage: {
    width: 200,
    height: 200,
    alignSelf: 'center',
    marginTop: 20,
  },

  centerText: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
});

export default styles;
